# Generated by Django 3.0 on 2020-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='op2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
